const LandObj = {
  en_US: {
    please_enter_account: "Please enter a username. ",
    please_enter_pwd: "Please enter a password.",
    please_enter_access_code: "Please enter an access code.",
    login: "Login",
    accesscode: "Access Code",
    password: "Password",
    account: "Account",
    or: "or",
    one_click_login: "One-click Login",
    account_login: "Account Login",
    voucher_login: "Voucher Login",
    forgot_password: "Forgot password?",
    register: "Register",
    welcome_title: "Welcome to iOrder",
    welcome_tagline: "Fast. Simple. Reliable ordering portal.",
    login_subtitle: "Secure access for your workspace",
    security_note: "Protected by iOrder secure authentication.",
    wifi_connect: "Connect Free WiFi",
    campaign_badge: "WiFi Marketing by iOrder",
    promo_title: "Free WiFi access. Get instant in-store offers.",
    promo_desc: "Connect to iOrder WiFi to receive vouchers, rewards and the latest promotions.",
    benefit_1_title: "Time-based Promotions",
    benefit_1_desc: "Get special coupons instantly during golden hours.",
    benefit_2_title: "Member Rewards",
    benefit_2_desc: "Unlock more perks each time you visit and stay connected.",
    benefit_3_title: "Faster Service",
    benefit_3_desc: "Order and pay more conveniently with the iOrder ecosystem.",
    voucher_capture_title: "Get a voucher before WiFi access",
    phone_placeholder: "Phone number",
    email_placeholder: "Email address",
    voucher_optin: "I agree to receive offers from iOrder.",
    lead_required: "Please enter phone number or email to receive voucher.",
    lead_phone_invalid: "Please enter a valid phone number.",
    lead_email_invalid: "Please enter a valid email address.",
    wifi_form_title: "Quick Survey Before WiFi Access",
    wifi_form_subtitle: "Answer in 10 seconds to unlock WiFi and receive tailored offers.",
    survey_age_label: "Your age range",
    select_age: "Select your age range",
    age_under_18: "Under 18",
    age_18_24: "18 - 24",
    age_25_34: "25 - 34",
    age_35_44: "35 - 44",
    age_45_plus: "45+",
    survey_consent: "I agree to receive promotional updates from iOrder.",
    wifi_enter_now: "Enter WiFi Now",
    age_required: "Please select your age range.",
  },
  vi_VN: {
    please_enter_account: "Vui lòng nhập tài khoản.",
    please_enter_pwd: "Vui lòng nhập mật khẩu.",
    please_enter_access_code: "Vui lòng nhập mã truy cập.",
    login: "Đăng nhập",
    accesscode: "Mã truy cập",
    password: "Mật khẩu",
    account: "Tài khoản",
    or: "hoặc",
    one_click_login: "Đăng nhập 1 chạm",
    account_login: "Đăng nhập tài khoản",
    voucher_login: "Đăng nhập bằng mã",
    forgot_password: "Quên mật khẩu?",
    register: "Đăng ký",
    welcome_title: "Chào mừng đến iOrder",
    welcome_tagline: "Nhanh. Đơn giản. Tin cậy.",
    login_subtitle: "Truy cập an toàn cho không gian làm việc của bạn",
    security_note: "Được bảo vệ bởi xác thực bảo mật iOrder.",
    wifi_connect: "Truy cập WiFi miễn phí",
    campaign_badge: "WiFi Marketing by iOrder",
    promo_title: "Vào mạng miễn phí. Nhận ưu đãi tại cửa hàng ngay.",
    promo_desc: "Kết nối WiFi iOrder để nhận voucher, tích điểm và cập nhật ưu đãi mới nhất.",
    benefit_1_title: "Ưu đãi theo thời điểm",
    benefit_1_desc: "Nhận mã giảm giá theo khung giờ vàng ngay khi online.",
    benefit_2_title: "Quà tặng thành viên",
    benefit_2_desc: "Mỗi lần quay lại, bạn nhận thêm quyền lợi và tích lũy điểm thưởng.",
    benefit_3_title: "Dịch vụ nhanh hơn",
    benefit_3_desc: "Đặt món, gọi món và thanh toán tiện lợi với hệ sinh thái iOrder.",
    voucher_capture_title: "Nhận voucher ưu đãi trước khi vào WiFi",
    phone_placeholder: "Số điện thoại",
    email_placeholder: "Email",
    voucher_optin: "Tôi đồng ý nhận ưu đãi từ iOrder.",
    lead_required: "Vui lòng nhập SĐT hoặc email để nhận voucher.",
    lead_phone_invalid: "Số điện thoại chưa hợp lệ.",
    lead_email_invalid: "Email chưa hợp lệ.",
    wifi_form_title: "Khảo sát nhanh để vào WiFi",
    wifi_form_subtitle: "Chỉ mất 10 giây để mở WiFi và nhận ưu đãi cá nhân hóa.",
    survey_age_label: "Độ tuổi của bạn",
    select_age: "Chọn độ tuổi",
    age_under_18: "Dưới 18",
    age_18_24: "18 - 24",
    age_25_34: "25 - 34",
    age_35_44: "35 - 44",
    age_45_plus: "45+",
    survey_consent: "Tôi đồng ý nhận thông tin ưu đãi từ iOrder.",
    wifi_enter_now: "Vào WiFi ngay",
    age_required: "Vui lòng chọn độ tuổi của bạn.",
  },
  es_ES: {
    please_enter_account: "Introduzca el nombre de usuario.",
    please_enter_pwd: "Introduzca la contraseña.",
    please_enter_access_code: "por favor ingrese el código de verificación.",
    login: "Iniciar sesión",
    accesscode: "Código de acceso",
    password: "Contraseña",
    account: "Cuenta",
    or: "o",
    one_click_login: "Un solo clic",
    account_login: "Cuenta",
    voucher_login: "Gutschein-Anmeldung",
    forgot_password: "¿Olvidó su contraseña?",
    register: "Registrarse",
    welcome_title: "Bienvenido a iOrder",
    welcome_tagline: "Portal de pedidos rápido, sencillo y fiable.",
    login_subtitle: "Acceso seguro para su espacio de trabajo",
    security_note: "Protegido por autenticación segura de iOrder.",
    wifi_connect: "Conectarse a WiFi gratis",
    campaign_badge: "WiFi Marketing by iOrder",
    promo_title: "Acceso WiFi gratis. Obtén ofertas instantáneas en tienda.",
    promo_desc: "Conéctate al WiFi de iOrder para recibir cupones, recompensas y promociones nuevas.",
    benefit_1_title: "Promociones por horario",
    benefit_1_desc: "Obtén cupones especiales al instante en horas clave.",
    benefit_2_title: "Recompensas para miembros",
    benefit_2_desc: "Recibe más beneficios cada vez que regreses.",
    benefit_3_title: "Servicio más rápido",
    benefit_3_desc: "Ordena y paga con mayor comodidad con el ecosistema iOrder.",
    voucher_capture_title: "Recibe un cupón antes de acceder al WiFi",
    phone_placeholder: "Número de teléfono",
    email_placeholder: "Correo electrónico",
    voucher_optin: "Acepto recibir ofertas de iOrder.",
    lead_required: "Ingrese teléfono o correo para recibir cupón.",
    lead_phone_invalid: "Número de teléfono no válido.",
    lead_email_invalid: "Correo electrónico no válido.",
    wifi_form_title: "Encuesta rápida antes de acceder al WiFi",
    wifi_form_subtitle: "Responde en 10 segundos para desbloquear WiFi y recibir ofertas personalizadas.",
    survey_age_label: "Tu rango de edad",
    select_age: "Selecciona tu rango de edad",
    age_under_18: "Menor de 18",
    age_18_24: "18 - 24",
    age_25_34: "25 - 34",
    age_35_44: "35 - 44",
    age_45_plus: "45+",
    survey_consent: "Acepto recibir actualizaciones promocionales de iOrder.",
    wifi_enter_now: "Entrar al WiFi ahora",
    age_required: "Seleccione su rango de edad.",
  },
};
